/**
 * Cart collection accessor (Firestore).
 * One cart per user — the user's id is used as the cart document id, which
 * enforces uniqueness for free.
 *
 * Document shape:
 *   { user, items: [{ id, product, quantity, customization }], createdAt, updatedAt }
 *
 * Each item carries a uuid string `id` (generated by the controller) so that
 * update/remove flows can identify items inside the same array.
 */
const { getDb } = require('../services/db');

const COLLECTION = 'carts';

const collection = () => getDb().collection(COLLECTION);

const docForUser = (userId) => collection().doc(userId);

const serialize = (snap) => {
  if (!snap || !snap.exists) return null;
  return { id: snap.id, ...snap.data() };
};

module.exports = { COLLECTION, collection, docForUser, serialize };
